# variables

VM_IMAGE = "centos/8"
NODES = 2

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "master" do |master|
    master.vm.box = VM_IMAGE
    master.vm.network "private_network", ip: "192.168.10.10"
    master.vm.hostname = "master"
    master.vbguest.installer_options = { allow_kernel_upgrade: true }
  end

  (1..NODES).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = VM_IMAGE
      node.vm.network "private_network", ip: "192.168.10.#{i + 20}"
      node.vm.hostname = "node#{i}"
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
    end
  end
end
